name: test
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
      - uses: actions/checkout@v2

      - name: start/test container
      - run: docker-compose run --rm aei-contract npm test

      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down